### ISSUE TITLE
Main discussion

### ISSUE THREAD

**Issue by Alovchin91** [Alovchin91/WinRTDesktopInterop#1]
This is the main discussion thread for the repository. One of the main reasons it is here is to link the repo to the original issue (Microsoft/cppwinrt#256) in Microsoft/cppwinrt repo.

**Comment by MichaelVach** [comment]
It looks like Microsoft has finally addressed this issue see [here](https://blogs.windows.com/windowsdeveloper/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/):
